[package]
name = "tcp_server_client_syscall"
version = "0.1.0"
edition = "2018"

[dependencies]
libc = "0.2"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"
