[package]
name = "lifetime_errors_v1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "4.0"
tokio = { version = "1", features = ["full"] }
log = "0.4"
lazy_static = "1.4"
rand = "0.8"